### ISSUE TITLE
v2ex图片无法显示

### ISSUE THREAD

**Issue by brucmao** [lisonge/v2ex-comment-markdown#1]
![image](https://user-images.githubusercontent.com/6119652/187592262-d8fd98c0-a8ff-4244-8e98-5e647f90ae07.png)
禁用脚本才能显示
![image](https://user-images.githubusercontent.com/6119652/187592334-d6a4dc7a-eb69-4518-a95c-e083bbe45e15.png)

**Comment by lisonge** [comment]
把你的其他关于评论的插件的这个功能关掉
![image](https://user-images.githubusercontent.com/38517192/187592679-6a9dbf35-e5a7-4fbc-9469-dd04181fe163.png)

**Comment by brucmao** [comment]
我原来用的[v2ex pro](https://greasyfork.org/en/scripts/397787-v2ex-pro) ，看了下v2ex 增强更好一点，可以单独禁用相关功能
