### ISSUE TITLE
v2ex多行显示异常

### ISSUE THREAD

**Issue by brucmao** [lisonge/v2ex-comment-markdown#3]
帖子：https://www.v2ex.com/t/874897  第8楼
启用脚本后
![image](https://user-images.githubusercontent.com/6119652/191183192-3aa33111-7215-42b1-ae16-777b48af6090.png)
关闭脚本
![image](https://user-images.githubusercontent.com/6119652/191183106-92c73b10-2739-424a-9fdf-7451db954916.png)

**Comment by lisonge** [comment]
fixed by <https://github.com/lisonge/v2ex-comment-markdown/commit/dcb1e5ab513460281109acdedac69d9b2cbedd16>

![image](https://user-images.githubusercontent.com/38517192/191189405-eac50bdf-208b-4cab-b0a3-c122425f6aa9.png)

**Comment by brucmao** [comment]
> fixed by [dcb1e5a](https://github.com/lisonge/v2ex-comment-markdown/commit/dcb1e5ab513460281109acdedac69d9b2cbedd16)
> 
> ![image](https://user-images.githubusercontent.com/38517192/191189405-eac50bdf-208b-4cab-b0a3-c122425f6aa9.png)

修复之后还是显示2行，这个应该时3行吧
单个反引号 ` 没关闭解析成markdown了么

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/191193943-6a7e549d-8705-466b-abb4-956853844ab4.png)
![image](https://user-images.githubusercontent.com/38517192/191194015-63b8d991-1ed9-49dc-b168-6178812b4b2c.png)

**Comment by brucmao** [comment]
我看错了，最后还有一个反引号
